name: prody
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - pip:
      - biopython==1.79
      - numpy==1.23.5
      - prody==2.4.1
      - pyparsing==3.1.1
      - scipy==1.13.0



